import type { Product, Supplier, StockTransaction, InventoryAlert, User } from "./types"

// Mock suppliers
export const mockSuppliers: Supplier[] = [
  {
    id: "SUP001",
    name: "TechParts Global",
    contactPerson: "John Smith",
    email: "john@techparts.com",
    phone: "+1-555-0101",
    address: "123 Industrial Ave, San Francisco, CA",
    rating: 4.8,
    totalOrders: 1250,
    onTimeDelivery: 96,
    status: "active",
  },
  {
    id: "SUP002",
    name: "ElectroSupply Inc",
    contactPerson: "Sarah Johnson",
    email: "sarah@electrosupply.com",
    phone: "+1-555-0102",
    address: "456 Commerce Blvd, Austin, TX",
    rating: 4.5,
    totalOrders: 890,
    onTimeDelivery: 92,
    status: "active",
  },
  {
    id: "SUP003",
    name: "Component Masters",
    contactPerson: "Michael Chen",
    email: "michael@componentmasters.com",
    phone: "+1-555-0103",
    address: "789 Tech Park, Seattle, WA",
    rating: 4.9,
    totalOrders: 2100,
    onTimeDelivery: 98,
    status: "active",
  },
  {
    id: "SUP004",
    name: "Hardware Direct",
    contactPerson: "Emily Davis",
    email: "emily@hardwaredirect.com",
    phone: "+1-555-0104",
    address: "321 Supply Chain Dr, Chicago, IL",
    rating: 4.3,
    totalOrders: 650,
    onTimeDelivery: 88,
    status: "active",
  },
  {
    id: "SUP005",
    name: "Global Parts Network",
    contactPerson: "David Wilson",
    email: "david@globalparts.com",
    phone: "+1-555-0105",
    address: "555 Distribution Way, Boston, MA",
    rating: 4.6,
    totalOrders: 1450,
    onTimeDelivery: 94,
    status: "inactive",
  },
]

// Mock products
export const mockProducts: Product[] = [
  {
    id: "PROD001",
    sku: "CPU-I9-13900K",
    name: "Intel Core i9-13900K Processor",
    category: "Processors",
    description: "High-performance desktop processor",
    price: 589.99,
    cost: 420.0,
    currentStock: 145,
    minStockLevel: 50,
    maxStockLevel: 300,
    reorderPoint: 75,
    supplierId: "SUP001",
    location: "Warehouse A - Aisle 3",
    lastRestocked: new Date("2025-01-15"),
    status: "in-stock",
  },
  {
    id: "PROD002",
    sku: "GPU-RTX-4090",
    name: "NVIDIA RTX 4090 Graphics Card",
    category: "Graphics Cards",
    description: "Premium gaming graphics card",
    price: 1599.99,
    cost: 1200.0,
    currentStock: 23,
    minStockLevel: 30,
    maxStockLevel: 100,
    reorderPoint: 40,
    supplierId: "SUP002",
    location: "Warehouse A - Aisle 5",
    lastRestocked: new Date("2025-01-10"),
    status: "low-stock",
  },
  {
    id: "PROD003",
    sku: "RAM-DDR5-32GB",
    name: "Corsair Vengeance DDR5 32GB",
    category: "Memory",
    description: "High-speed DDR5 memory kit",
    price: 159.99,
    cost: 110.0,
    currentStock: 0,
    minStockLevel: 100,
    maxStockLevel: 500,
    reorderPoint: 150,
    supplierId: "SUP003",
    location: "Warehouse B - Aisle 2",
    lastRestocked: new Date("2024-12-20"),
    status: "out-of-stock",
  },
  {
    id: "PROD004",
    sku: "SSD-NVME-2TB",
    name: "Samsung 990 PRO 2TB NVMe SSD",
    category: "Storage",
    description: "Ultra-fast NVMe solid state drive",
    price: 199.99,
    cost: 145.0,
    currentStock: 287,
    minStockLevel: 80,
    maxStockLevel: 400,
    reorderPoint: 120,
    supplierId: "SUP001",
    location: "Warehouse B - Aisle 4",
    lastRestocked: new Date("2025-01-18"),
    status: "in-stock",
  },
  {
    id: "PROD005",
    sku: "MB-Z790-GAMING",
    name: "ASUS ROG Z790 Motherboard",
    category: "Motherboards",
    description: "Premium gaming motherboard",
    price: 449.99,
    cost: 320.0,
    currentStock: 67,
    minStockLevel: 40,
    maxStockLevel: 150,
    reorderPoint: 60,
    supplierId: "SUP002",
    location: "Warehouse A - Aisle 7",
    lastRestocked: new Date("2025-01-12"),
    status: "in-stock",
  },
  {
    id: "PROD006",
    sku: "PSU-850W-GOLD",
    name: "EVGA SuperNOVA 850W Gold PSU",
    category: "Power Supplies",
    description: "80+ Gold certified power supply",
    price: 129.99,
    cost: 85.0,
    currentStock: 156,
    minStockLevel: 60,
    maxStockLevel: 250,
    reorderPoint: 90,
    supplierId: "SUP004",
    location: "Warehouse C - Aisle 1",
    lastRestocked: new Date("2025-01-14"),
    status: "in-stock",
  },
  {
    id: "PROD007",
    sku: "CASE-MID-RGB",
    name: "NZXT H510 Elite RGB Case",
    category: "Cases",
    description: "Mid-tower gaming case with RGB",
    price: 149.99,
    cost: 95.0,
    currentStock: 42,
    minStockLevel: 30,
    maxStockLevel: 120,
    reorderPoint: 45,
    supplierId: "SUP003",
    location: "Warehouse C - Aisle 5",
    lastRestocked: new Date("2025-01-08"),
    status: "in-stock",
  },
  {
    id: "PROD008",
    sku: "COOL-AIO-360",
    name: "Corsair iCUE H150i Elite 360mm AIO",
    category: "Cooling",
    description: "Premium liquid cooling system",
    price: 189.99,
    cost: 130.0,
    currentStock: 18,
    minStockLevel: 25,
    maxStockLevel: 100,
    reorderPoint: 35,
    supplierId: "SUP001",
    location: "Warehouse A - Aisle 6",
    lastRestocked: new Date("2025-01-05"),
    status: "low-stock",
  },
  {
    id: "PROD009",
    sku: "MON-4K-27",
    name: 'LG UltraGear 27" 4K Monitor',
    category: "Monitors",
    description: "4K gaming monitor 144Hz",
    price: 599.99,
    cost: 425.0,
    currentStock: 89,
    minStockLevel: 40,
    maxStockLevel: 150,
    reorderPoint: 60,
    supplierId: "SUP002",
    location: "Warehouse B - Aisle 8",
    lastRestocked: new Date("2025-01-16"),
    status: "in-stock",
  },
  {
    id: "PROD010",
    sku: "KB-MECH-RGB",
    name: "Razer BlackWidow V4 Mechanical Keyboard",
    category: "Peripherals",
    description: "RGB mechanical gaming keyboard",
    price: 179.99,
    cost: 115.0,
    currentStock: 234,
    minStockLevel: 80,
    maxStockLevel: 300,
    reorderPoint: 120,
    supplierId: "SUP004",
    location: "Warehouse C - Aisle 3",
    lastRestocked: new Date("2025-01-19"),
    status: "in-stock",
  },
]

// Mock stock transactions
export const mockTransactions: StockTransaction[] = [
  {
    id: "TXN001",
    productId: "PROD001",
    type: "purchase",
    quantity: 100,
    previousStock: 45,
    newStock: 145,
    timestamp: new Date("2025-01-15T10:30:00"),
    userId: "USR001",
    notes: "Restocking order from TechParts Global",
  },
  {
    id: "TXN002",
    productId: "PROD002",
    type: "sale",
    quantity: -12,
    previousStock: 35,
    newStock: 23,
    timestamp: new Date("2025-01-20T14:15:00"),
    userId: "USR002",
    notes: "Bulk order for gaming cafe",
  },
  {
    id: "TXN003",
    productId: "PROD003",
    type: "sale",
    quantity: -45,
    previousStock: 45,
    newStock: 0,
    timestamp: new Date("2025-01-21T09:00:00"),
    userId: "USR002",
    notes: "Large corporate order",
  },
  {
    id: "TXN004",
    productId: "PROD004",
    type: "purchase",
    quantity: 150,
    previousStock: 137,
    newStock: 287,
    timestamp: new Date("2025-01-18T11:45:00"),
    userId: "USR001",
    notes: "Regular restocking",
  },
  {
    id: "TXN005",
    productId: "PROD008",
    type: "sale",
    quantity: -7,
    previousStock: 25,
    newStock: 18,
    timestamp: new Date("2025-01-21T16:20:00"),
    userId: "USR002",
    notes: "Retail sales",
  },
]

// Mock alerts
export const mockAlerts: InventoryAlert[] = [
  {
    id: "ALT001",
    productId: "PROD003",
    productName: "Corsair Vengeance DDR5 32GB",
    type: "out-of-stock",
    severity: "high",
    message: "Product is completely out of stock. Immediate reorder required.",
    timestamp: new Date("2025-01-21T09:05:00"),
  },
  {
    id: "ALT002",
    productId: "PROD002",
    productName: "NVIDIA RTX 4090 Graphics Card",
    type: "low-stock",
    severity: "high",
    message: "Stock level below minimum threshold (23 units remaining).",
    timestamp: new Date("2025-01-20T14:20:00"),
  },
  {
    id: "ALT003",
    productId: "PROD008",
    productName: "Corsair iCUE H150i Elite 360mm AIO",
    type: "low-stock",
    severity: "medium",
    message: "Stock approaching reorder point (18 units remaining).",
    timestamp: new Date("2025-01-21T16:25:00"),
  },
]

// Mock users
export const mockUsers: User[] = [
  {
    id: "USR001",
    email: "admin@inventory.com",
    name: "Admin User",
    role: "admin",
  },
  {
    id: "USR002",
    email: "manager@inventory.com",
    name: "Inventory Manager",
    role: "manager",
  },
  {
    id: "USR003",
    email: "supplier@techparts.com",
    name: "Supplier Portal",
    role: "supplier",
  },
]

// Analytics data generators
export function generateStockTrendData() {
  const days = 30
  const data = []
  for (let i = days; i >= 0; i--) {
    const date = new Date()
    date.setDate(date.getDate() - i)
    data.push({
      date: date.toISOString().split("T")[0],
      inStock: Math.floor(Math.random() * 500) + 1200,
      lowStock: Math.floor(Math.random() * 50) + 20,
      outOfStock: Math.floor(Math.random() * 15) + 5,
    })
  }
  return data
}

export function generateCategoryDistribution() {
  return [
    { category: "Processors", value: 145, percentage: 12 },
    { category: "Graphics Cards", value: 23, percentage: 2 },
    { category: "Memory", value: 0, percentage: 0 },
    { category: "Storage", value: 287, percentage: 24 },
    { category: "Motherboards", value: 67, percentage: 6 },
    { category: "Power Supplies", value: 156, percentage: 13 },
    { category: "Cases", value: 42, percentage: 4 },
    { category: "Cooling", value: 18, percentage: 2 },
    { category: "Monitors", value: 89, percentage: 7 },
    { category: "Peripherals", value: 234, percentage: 20 },
  ]
}

export function generateRevenueData() {
  const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
  return months.map((month) => ({
    month,
    revenue: Math.floor(Math.random() * 500000) + 300000,
    cost: Math.floor(Math.random() * 300000) + 200000,
  }))
}

export function generateSupplierPerformance() {
  return mockSuppliers.map((supplier) => ({
    name: supplier.name,
    onTimeDelivery: supplier.onTimeDelivery,
    rating: supplier.rating,
    totalOrders: supplier.totalOrders,
  }))
}
